"""
MUMT-v2 model for event-aware AFFEC features.

This model consumes the wide table generated by `preprocess_v2.py`. It does
not assume shared temporal downsampling. Instead, feature columns are grouped
into modality/event tokens, encoded independently, fused with a Transformer,
and decoded with separate felt/perceived emotion heads plus gap heads.
"""

from __future__ import annotations

from collections import OrderedDict
from dataclasses import dataclass
from typing import Mapping, Optional, Sequence

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F

from mumtaffect.event_features import EVENT_FLAGS


TASK_NAMES = (
    "felt_arousal",
    "felt_valence",
    "perceived_arousal",
    "perceived_valence",
)

MODALITY_PREFIXES = (
    "eye__",
    "pupil__",
    "au__",
    "gsr__",
    "cursor__",
    "eeg__",
)

CONDITIONING_GROUP_PREFIXES = (
    "profile",
    "context",
    "audio",
    "labelstyle",
)

EVENT_NAMES = (*EVENT_FLAGS, "video_minus_baseline")


@dataclass
class MUMTV2Output:
    emotion_logits: torch.Tensor
    rating_raw: torch.Tensor
    gap_raw: torch.Tensor
    fused_embedding: torch.Tensor
    task_embeddings: torch.Tensor
    group_embeddings: torch.Tensor


def infer_feature_group(column_name: str) -> str:
    """Map a feature column into an auditable model token group."""
    if column_name.startswith("quality__"):
        parts = column_name.split("__")
        if len(parts) >= 4:
            return f"quality:{parts[1]}:{parts[2]}"
        return "quality"

    if column_name.startswith("event__"):
        parts = column_name.split("__")
        return f"event:{parts[1]}" if len(parts) >= 2 else "event"

    for prefix in MODALITY_PREFIXES:
        if not column_name.startswith(prefix):
            continue
        modality = prefix[:-2]
        remainder = column_name[len(prefix):]
        event_name = remainder.split("__", 1)[0]
        if event_name in EVENT_NAMES:
            return f"{modality}:{event_name}"
        return modality

    if column_name.startswith("profile__"):
        return "profile"
    if column_name.startswith("context__"):
        return "context"
    if column_name.startswith("audio__"):
        return "audio"
    if column_name.startswith("labelstyle__"):
        return "labelstyle"
    if column_name.startswith("foundation__"):
        parts = column_name.split("__")
        return f"foundation:{parts[1]}" if len(parts) >= 2 else "foundation"

    return "misc"


def build_feature_groups(feature_columns: Sequence[str]) -> OrderedDict[str, list[int]]:
    groups: dict[str, list[int]] = {}
    for feature_index, column_name in enumerate(feature_columns):
        group_name = infer_feature_group(column_name)
        groups.setdefault(group_name, []).append(feature_index)
    return OrderedDict((group_name, groups[group_name]) for group_name in sorted(groups))


def init_weights(module: nn.Module) -> None:
    if isinstance(module, nn.Linear):
        nn.init.xavier_uniform_(module.weight)
        if module.bias is not None:
            nn.init.zeros_(module.bias)


class FeatureGroupEncoder(nn.Module):
    """Encode one feature group into one Transformer token."""

    def __init__(self, input_dim: int, d_model: int, dropout: float):
        super().__init__()
        hidden_dim = max(d_model, min(512, input_dim * 2))
        self.net = nn.Sequential(
            nn.Linear(input_dim, hidden_dim),
            nn.LayerNorm(hidden_dim),
            nn.GELU(),
            nn.Dropout(dropout),
            nn.Linear(hidden_dim, d_model),
            nn.LayerNorm(d_model),
            nn.GELU(),
        )
        self.apply(init_weights)

    def forward(self, features: torch.Tensor) -> torch.Tensor:
        return self.net(features)


class TaskHead(nn.Module):
    """One classification and one raw-rating regression head for an emotion task."""

    def __init__(self, input_dim: int, hidden_dim: int, n_classes: int, dropout: float):
        super().__init__()
        self.shared = nn.Sequential(
            nn.LayerNorm(input_dim),
            nn.Linear(input_dim, hidden_dim),
            nn.GELU(),
            nn.Dropout(dropout),
        )
        self.classifier = nn.Linear(hidden_dim, n_classes)
        self.rating = nn.Linear(hidden_dim, 1)
        self.apply(init_weights)

    def forward(self, task_embedding: torch.Tensor, global_embedding: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor]:
        features = torch.cat([task_embedding, global_embedding], dim=-1)
        hidden = self.shared(features)
        logits = self.classifier(hidden)
        rating = 1.0 + 8.0 * torch.sigmoid(self.rating(hidden).squeeze(-1))
        return logits, rating


class MUMTV2Model(nn.Module):
    """
    Event-token Transformer for MUMT-v2.

    Inputs:
        features: `(batch, n_features)` using `dataset_v2.select_feature_columns`.
        user_prototype: optional few-shot prototype `(batch, d_model)` or `(d_model,)`.

    Outputs:
        `MUMTV2Output` with 4 emotion logits, 4 raw ratings, 2 felt/perceived gaps,
        and embeddings that can be reused for prototype-based adaptation.
    """

    def __init__(
        self,
        feature_columns: Sequence[str],
        d_model: int = 128,
        n_heads: int = 4,
        n_layers: int = 2,
        hidden_dim: int = 256,
        n_classes: int = 3,
        dropout: float = 0.15,
        modality_dropout_p: float = 0.10,
        foundation_gate: bool = False,
        foundation_gate_init: float = -2.0,
    ):
        super().__init__()
        if d_model % n_heads != 0:
            raise ValueError("d_model must be divisible by n_heads.")

        self.feature_columns = list(feature_columns)
        self.feature_groups = build_feature_groups(self.feature_columns)
        self.group_names = list(self.feature_groups.keys())
        self.d_model = d_model
        self.n_classes = n_classes
        self.modality_dropout_p = modality_dropout_p
        self.foundation_gate = foundation_gate

        self.group_encoders = nn.ModuleDict()
        self.group_index_buffer_names: list[str] = []
        for group_index, (group_name, feature_indices) in enumerate(self.feature_groups.items()):
            safe_group_name = group_name.replace(":", "__")
            self.group_encoders[safe_group_name] = FeatureGroupEncoder(len(feature_indices), d_model, dropout)
            buffer_name = f"group_indices_{group_index}"
            self.register_buffer(buffer_name, torch.tensor(feature_indices, dtype=torch.long), persistent=False)
            self.group_index_buffer_names.append(buffer_name)

        self.group_type_embedding = nn.Embedding(max(1, len(self.group_names)), d_model)
        self.foundation_positions = [
            group_index for group_index, group_name in enumerate(self.group_names)
            if group_name.startswith("foundation")
        ]
        if foundation_gate and self.foundation_positions:
            self.foundation_gate_logits = nn.Parameter(
                torch.full((len(self.foundation_positions),), float(foundation_gate_init))
            )
        else:
            self.register_parameter("foundation_gate_logits", None)
        self.cls_token = nn.Parameter(torch.zeros(1, 1, d_model))
        self.task_queries = nn.Parameter(torch.randn(1, len(TASK_NAMES), d_model) * 0.02)

        transformer_layer = nn.TransformerEncoderLayer(
            d_model=d_model,
            nhead=n_heads,
            dim_feedforward=hidden_dim * 2,
            dropout=dropout,
            activation="gelu",
            batch_first=True,
            norm_first=False,
        )
        self.fusion = nn.TransformerEncoder(transformer_layer, num_layers=n_layers)
        self.final_norm = nn.LayerNorm(d_model)

        self.condition_positions = [
            group_index for group_index, group_name in enumerate(self.group_names)
            if group_name.split(":", 1)[0] in CONDITIONING_GROUP_PREFIXES
        ]
        self.condition_gate = nn.Sequential(
            nn.LayerNorm(d_model),
            nn.Linear(d_model, d_model),
            nn.Sigmoid(),
        )

        self.prototype_adapter = nn.Sequential(
            nn.LayerNorm(d_model),
            nn.Linear(d_model, d_model),
            nn.GELU(),
            nn.Dropout(dropout),
            nn.Linear(d_model, d_model),
        )

        head_input_dim = d_model * 2
        self.task_heads = nn.ModuleDict({
            task_name: TaskHead(head_input_dim, hidden_dim, n_classes, dropout)
            for task_name in TASK_NAMES
        })
        self.gap_head = nn.Sequential(
            nn.LayerNorm(d_model * 3),
            nn.Linear(d_model * 3, hidden_dim),
            nn.GELU(),
            nn.Dropout(dropout),
            nn.Linear(hidden_dim, 2),
        )

        self.apply(init_weights)
        nn.init.normal_(self.cls_token, std=0.02)

    def _encode_group_tokens(self, features: torch.Tensor) -> torch.Tensor:
        group_tokens = []
        for group_index, group_name in enumerate(self.group_names):
            safe_group_name = group_name.replace(":", "__")
            feature_indices = getattr(self, self.group_index_buffer_names[group_index])
            group_features = torch.index_select(features, dim=1, index=feature_indices)
            group_features = torch.nan_to_num(group_features, nan=0.0, posinf=0.0, neginf=0.0)
            token = self.group_encoders[safe_group_name](group_features)
            token = token + self.group_type_embedding.weight[group_index]
            group_tokens.append(token)

        if not group_tokens:
            return torch.zeros(features.size(0), 0, self.d_model, device=features.device)

        tokens = torch.stack(group_tokens, dim=1)
        if self.foundation_gate_logits is not None:
            foundation_indices = torch.tensor(self.foundation_positions, device=tokens.device)
            gates = torch.sigmoid(self.foundation_gate_logits).view(1, -1, 1)
            tokens[:, foundation_indices, :] = tokens[:, foundation_indices, :] * gates
        if self.training and self.modality_dropout_p > 0:
            keep_mask = torch.rand(tokens.size(0), tokens.size(1), 1, device=tokens.device) > self.modality_dropout_p
            tokens = tokens * keep_mask.float()
        return tokens

    def encode_features(
        self,
        features: torch.Tensor,
        user_prototype: Optional[torch.Tensor] = None,
    ) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
        batch_size = features.size(0)
        group_tokens = self._encode_group_tokens(features)
        cls_token = self.cls_token.expand(batch_size, -1, -1)
        task_queries = self.task_queries.expand(batch_size, -1, -1)
        token_sequence = torch.cat([cls_token, group_tokens, task_queries], dim=1)
        encoded_tokens = self.final_norm(self.fusion(token_sequence))

        fused_embedding = encoded_tokens[:, 0]
        group_embeddings = encoded_tokens[:, 1:1 + len(self.group_names)]
        task_embeddings = encoded_tokens[:, 1 + len(self.group_names):]

        if self.condition_positions:
            condition_indices = torch.tensor(self.condition_positions, device=features.device)
            condition_embedding = torch.index_select(group_embeddings, dim=1, index=condition_indices).mean(dim=1)
            fused_embedding = fused_embedding * (0.5 + self.condition_gate(condition_embedding))

        if user_prototype is not None:
            if user_prototype.dim() == 1:
                user_prototype = user_prototype.unsqueeze(0).expand(batch_size, -1)
            prototype_update = self.prototype_adapter(user_prototype)
            fused_embedding = fused_embedding + prototype_update
            task_embeddings = task_embeddings + prototype_update.unsqueeze(1)

        return fused_embedding, task_embeddings, group_embeddings

    def embed_features(self, features: torch.Tensor) -> torch.Tensor:
        fused_embedding, _, _ = self.encode_features(features)
        return fused_embedding

    def make_user_prototype(self, support_features: torch.Tensor) -> torch.Tensor:
        support_embeddings = self.embed_features(support_features)
        return support_embeddings.mean(dim=0)

    def forward(
        self,
        features: torch.Tensor,
        user_prototype: Optional[torch.Tensor] = None,
    ) -> MUMTV2Output:
        fused_embedding, task_embeddings, group_embeddings = self.encode_features(features, user_prototype)

        logits_by_task = []
        ratings_by_task = []
        for task_index, task_name in enumerate(TASK_NAMES):
            logits, rating = self.task_heads[task_name](task_embeddings[:, task_index], fused_embedding)
            logits_by_task.append(logits)
            ratings_by_task.append(rating)

        emotion_logits = torch.stack(logits_by_task, dim=1)
        rating_raw = torch.stack(ratings_by_task, dim=1)

        felt_embedding = 0.5 * (task_embeddings[:, 0] + task_embeddings[:, 1])
        perceived_embedding = 0.5 * (task_embeddings[:, 2] + task_embeddings[:, 3])
        gap_features = torch.cat([felt_embedding, perceived_embedding, fused_embedding], dim=-1)
        gap_raw = self.gap_head(gap_features)

        return MUMTV2Output(
            emotion_logits=emotion_logits,
            rating_raw=rating_raw,
            gap_raw=gap_raw,
            fused_embedding=fused_embedding,
            task_embeddings=task_embeddings,
            group_embeddings=group_embeddings,
        )


class MUMTV2Loss(nn.Module):
    """Joint loss for binned emotions, raw ratings, and felt/perceived gaps."""

    def __init__(
        self,
        class_weights: Optional[torch.Tensor] = None,
        emotion_weight: float = 1.0,
        rating_weight: float = 0.25,
        gap_weight: float = 0.20,
        label_smoothing: float = 0.0,
    ):
        super().__init__()
        self.register_buffer("class_weights", class_weights if class_weights is not None else torch.empty(0))
        self.emotion_weight = emotion_weight
        self.rating_weight = rating_weight
        self.gap_weight = gap_weight
        self.label_smoothing = label_smoothing

    def _class_weight_for_task(self, task_index: int) -> Optional[torch.Tensor]:
        if self.class_weights.numel() == 0:
            return None
        if self.class_weights.dim() == 1:
            return self.class_weights
        return self.class_weights[task_index]

    def forward(
        self,
        output: MUMTV2Output,
        labels_bin: torch.Tensor,
        labels_raw: Optional[torch.Tensor] = None,
        labels_gap: Optional[torch.Tensor] = None,
    ) -> tuple[torch.Tensor, dict[str, float]]:
        total_loss = output.emotion_logits.sum() * 0.0
        components: dict[str, torch.Tensor] = {}

        emotion_losses = []
        for task_index, task_name in enumerate(TASK_NAMES):
            task_target = labels_bin[:, task_index].long()
            valid_mask = (task_target >= 0) & (task_target < output.emotion_logits.size(-1))
            if valid_mask.any():
                task_loss = F.cross_entropy(
                    output.emotion_logits[valid_mask, task_index],
                    task_target[valid_mask],
                    weight=self._class_weight_for_task(task_index),
                    label_smoothing=self.label_smoothing,
                )
                emotion_losses.append(task_loss)
                components[f"ce_{task_name}"] = task_loss.detach()

        if emotion_losses:
            emotion_loss = torch.stack(emotion_losses).mean()
            total_loss = total_loss + self.emotion_weight * emotion_loss
            components["emotion"] = emotion_loss.detach()

        if labels_raw is not None and self.rating_weight > 0:
            raw_mask = torch.isfinite(labels_raw)
            if raw_mask.any():
                rating_loss = F.smooth_l1_loss(output.rating_raw[raw_mask], labels_raw.float()[raw_mask])
                total_loss = total_loss + self.rating_weight * rating_loss
                components["rating"] = rating_loss.detach()

        if labels_gap is not None and self.gap_weight > 0:
            gap_mask = torch.isfinite(labels_gap)
            if gap_mask.any():
                gap_loss = F.smooth_l1_loss(output.gap_raw[gap_mask], labels_gap.float()[gap_mask])
                total_loss = total_loss + self.gap_weight * gap_loss
                components["gap"] = gap_loss.detach()

        component_values = {
            name: float(value.detach().cpu().item())
            for name, value in components.items()
        }
        component_values["total"] = float(total_loss.detach().cpu().item())
        return total_loss, component_values


def compute_class_weights(labels_bin: np.ndarray, n_classes: int = 3) -> torch.Tensor:
    """Return inverse-frequency class weights with shape `(4, n_classes)`."""
    labels_array = np.asarray(labels_bin)
    weights = np.ones((labels_array.shape[1], n_classes), dtype=np.float32)
    for task_index in range(labels_array.shape[1]):
        task_values = labels_array[:, task_index]
        valid_values = task_values[(task_values >= 0) & (task_values < n_classes)].astype(int)
        if valid_values.size == 0:
            continue
        counts = np.bincount(valid_values, minlength=n_classes).astype(np.float32)
        counts = np.maximum(counts, 1.0)
        task_weights = counts.sum() / (n_classes * counts)
        weights[task_index] = task_weights / task_weights.mean()
    return torch.tensor(weights, dtype=torch.float32)


def model_summary(feature_columns: Sequence[str]) -> Mapping[str, int]:
    """Compact feature-token summary for logging model configs."""
    groups = build_feature_groups(feature_columns)
    summary: OrderedDict[str, int] = OrderedDict()
    for group_name, feature_indices in groups.items():
        summary[group_name] = len(feature_indices)
    return summary
